default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: help_my_net_development

test:
  <<: *default
  database: help_my_net_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
